apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-acg
  region: ap-southeast-2
  version: "1.21"

vpc:
  cidr: 10.0.0.0/16

nodeGroups:
  - name: eks-node-group
    instanceType: t3a.small
    desiredCapacity: 1
    privateNetworking: true
